# Generated by Django 5.1.1 on 2024-09-25 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=200)),
                ('Image', models.ImageField(upload_to='images')),
                ('Price', models.CharField(max_length=255)),
                ('Description', models.CharField(max_length=400)),
                ('Color', models.CharField(max_length=100)),
            ],
        ),
    ]
