# Generated by Django 5.1.1 on 2024-09-25 08:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eccomerceApp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='Image',
            new_name='photo',
        ),
    ]
